### PR TITLE
better overpic, mrow, and other

### PR DESCRIPTION
**Pull request by davidfarmer**
The overpic should be as you wanted,
the mrow's should be as you wanted (no carriage return on the last one in the md),
the sections should not be in the index.mbx,
and the two "< " should now be "<lt />", so you can xsltproc the files as-is.
Maybe I also fixed something else, but I can't seem to remember what it was.

Let me know any remaining high-priority items.

GitHub tells me there is a merge conflict.  Not sure why.

### CODE REVIEW

**Comment by mitchkeller** [comment]
The merge conflicts are just because I'd done some mucking about with a couple of files in different ways than what your script did. Easy to resolve on my end, so don't worry about it. However, your `</mrow>` fix doesn't resolve the issue in LaTeX, so I'm not going to merge this.

In s_intro_number.mbx, you've got:

```
<md>
  <mrow>  351785000 \amp =  2^3\times 5^4\times 7\times19\times 23^2\quad\text{and}
      </mrow>
  <mrow>  316752027900 \amp =  2^2\times3\times 5^2\times 7^3\times 11\times 23^4.
      </mrow></md>
```
The problem is the new line before </mrow>, since `xsltproc` produces

```
\begin{align*}
  351785000 \amp =  2^3\times 5^4\times 7\times19\times 23^2\quad\text{and}
      \\
  316752027900 \amp =  2^2\times3\times 5^2\times 7^3\times 11\times 23^4.
      
\end{align*}\par
```

The LaTeX compilation process can handle the \\ being on its own line, but the blank line before `\end{align*}` is intolerable for it. The MBX, as best as I can tell, should be:

```
<md>
  <mrow>  351785000 \amp =  2^3\times 5^4\times 7\times19\times 23^2\quad\text{and}</mrow>
  <mrow>  316752027900 \amp =  2^2\times3\times 5^2\times 7^3\times 11\times 23^4.</mrow>
</md>
```

If I change to that, I get something without the extra line breaks in the LaTeX file. Can sl2x produce that?

**Comment by mitchkeller** [comment]
Overpic stuff looks spot on, though, I should say. Thanks for doing that!

**Comment by davidfarmer** [comment]
I set it so that the *last* mrow in an md does not have the
carriage return at the end.

Apparently that was not what is needed

Are you saying that we don't want a carrieage return *before*
any closing mrow?  And I can put a carriage return after every
closing mrow?

**Comment by mitchkeller** [comment]
I must have used some confusing phrasing earlier. The issue was never the carriage return after the `</mrow>` tag, it was the carriage return *inside* the mrow, specifically the one that comes before the closing `</mrow>`. To avoid mystery errors that arise from reordering or deleting equations, I would suggest that we *never* want a carriage return *before* a closing mrow, even though it's only the carriage return before the final closing mrow that causes problems in LaTeX. And yes, a carriage return *after* every closing mrow is fine. (The MBX I included in my previous comment produces exactly the HTML and LaTeX we want.)

**Comment by davidfarmer** [comment]
I updated the pull request.

Let me know if I need to do it as a new pull request.

**Comment by mitchkeller** [comment]
That's the ticket. I've merged this more or less seamlessly. I've got a couple of cleanup issues I'll have to script on my end once we designate final the final conversion (up to splitting exercises later in the summer), but I think things are almost there. I'm going to close this and make one more issue on your branch for something that I hope is an easy fix for you.

**Pull request closed without merging**
